# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Code Club"
  url = "codeclub/"
  weight = 20
  identifier = "codeclub"

[[main]]
  name = "- <b>About Code Club & Join!</b>"
  url = "codeclub-about/"
  weight = 10
  parent = "codeclub"

[[main]]
  name = "- <b>Schedule</b>"
  url = "codeclub-schedule/"
  weight = 20
  parent = "codeclub"

[[main]]
  name = "----------------------"
  url = ""
  weight = 30
  parent = "codeclub"

[[main]]
  name = "- All Past Sessions"
  url = "codeclub/"
  weight = 40
  parent = "codeclub"

[[main]]
  name = "- Suggest a Topic"
  url = "codeclub-suggest/"
  weight = 50
  parent = "codeclub"

[[main]]
  name = "-----------------------"
  url = ""
  weight = 60
  parent = "codeclub"

[[main]]
  name = "- Computer Setup"
  url = "codeclub-setup/"
  weight = 70
  parent = "codeclub"

[[main]]
  name = "- Getting Started with R"
  url = "codeclub-novice/"
  weight = 80
  parent = "codeclub"

[[main]]
  name = "- For Presenters"
  url = "codeclub-present/"
  weight = 90
  parent = "codeclub"

[[main]]
  name = "Other Events"
  url = "events/"
  weight = 40

[[main]]
  name = "Tutorials & more"
  url = "material/"
  weight = 50

[[main]]
  name = "Support"
  url = "support/"
  weight = 60

[[main]]
  name = "Suggest..."
  url = "suggest/"
  weight = 70

[[main]]
  name = "About"
  url = "about/"
  weight = 80

[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/biodash/biodash.github.io"
  weight = 90

[[main]]
  identifier = "rss"
  pre = "<i class='fas fa-rss'></i>"
  url = "https://biodash.github.io/index.xml"
  weight = 100



#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
